version: 2


sources:
  - name: database
    schema: database
    tables:
      - name: brands
      - name: categories
      - name: products
      - name: stocks
      - name: customers
      - name: order_items
      - name: orders
      - name: staffs
      - name: stores